### ISSUE TITLE
Any update on where this is currently for official use? 

### ISSUE THREAD

**Issue by xtianus79** [decentralized-identity/secure-data-store#3]
Any updates would be useful.

**Comment by tplooker** [comment]
This issue was discussed on the 07/05/2020 call and the suggested resolution was to close in the next week if there are no objections

**Comment by OR13** [comment]
@xtianus79 please feel free to ask questions on this repo, you are responsible for moving this issue forward, I would suggest closing this one, and contributing to the other issues.

**Comment by OR13** [comment]
Closing, due to inactivity
