### ISSUE TITLE
Input Documents Have been Archived and Pointed Here

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/secure-data-store#30]
- [x] https://github.com/decentralized-identity/identity-hub
- [x] https://github.com/digitalbazaar/encrypted-data-vaults

**Comment by OR13** [comment]
@msporny once you accept the invite as editor I will assign you.

**Comment by msporny** [comment]
Done: https://github.com/digitalbazaar/encrypted-data-vaults

**Comment by msporny** [comment]
Both redirects are in place and point to the new repo and spec. Closing.
