### ISSUE TITLE
Add back the vertical data examples to the Collections section of the explainer doc

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/secure-data-store#4]
@dstrockis noticed all the other verticals of data examples for Collections were erased (medical - HL7 FHIR, supply chain - GS1, etc.) in the last larger update to the doc - can we get some of these back in there, so folks can easily see the versatility of the Hub/Collections?

**Comment by tplooker** [comment]
Resolved on 07/05/2020 call
