### ISSUE TITLE
How should the architecture layers be named?

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/secure-data-store#44]
I recognize this is a bikeshed issue, so we should be mindful of this. Especially as we're still aligning on a mental model and architecture. To get things started though, I propose this set of names for the layers:

Layer 1: Storage layer
Layer 2: Replication layer
Layer 3: Integrity layer

**Comment by csuwildcat** [comment]
Just a thought:

Layer 1: Message Layer - required encryption, replication, and routing bits that must be integrated into messages

Layer 2: Storage Layer - messages are stored, managed, and permissioned as a coherent singular mass

Layer 3: Query Layer - how the storage layer groups, indexes, and exposes the data in the storage layer

**Comment by kdenhartog** [comment]
> 
> 
> Just a thought:
> 
> Layer 1: Message Layer - required encryption, replication, and routing bits that must be integrated into messages
> 
> Layer 2: Storage Layer - messages are stored, managed, and permissioned as a coherent singular mass
> 
> Layer 3: Query Layer - how the storage layer groups, indexes, and exposes the data in the storage layer

I'm good with those names.

**Comment by agropper** [comment]
I suggest we delay this layering exercise until after we name the key roles. In particular, I would wait for [w3c/did-use-cases] Relying Party -> Requesting Party ([#84](https://github.com/w3c/did-use-cases/pull/84))

**Comment by msporny** [comment]
-1, Messaging at the base layer is concerning, maybe?

**Comment by csuwildcat** [comment]
@msporny by messaging, I simply mean: the actual atomic objects sent between SDS instances, and the definitions of their required/standard properties and values the SDS system needs to properly handle them. Could also be referred to as Object Layer.

**Comment by msporny** [comment]
> Could also be referred to as Object Layer.

Right, agreed that "Object Layer" might be better... Getting a full list of features might be more helpful... once we have all of the features identified, then we can sort them into layers, IMHO.

**Comment by OR13** [comment]
Another proposal here: https://github.com/decentralized-identity/secure-data-store/issues/74

**Comment by kdenhartog** [comment]
In an effort to consolidate the threads around this discussion, I'll repost the proposals from this thread there and close it. See this https://github.com/decentralized-identity/secure-data-store/issues/74#issuecomment-645676378 for more details
