### ISSUE TITLE
Move 1.3.5 (Deployment Topologies) to section 1.2

### ISSUE THREAD

**Issue by ewelton** [decentralized-identity/secure-data-store#50]
I do not think that Deployment Topologies is a use-case - rather, it belongs in the ecosystem component where we establish the context and roles that are under discussion.

Also relates to #47.

**Comment by OR13** [comment]
With #53 merged, we are ready for a a PR that implements the changes suggested on this issue.

**Comment by OR13** [comment]
This appears to be done.
