### ISSUE TITLE
Prior art

### ISSUE THREAD

**Issue by ianopolous** [decentralized-identity/secure-data-store#56]
Is this an appropriate place to mention prior art? That is, existing open source systems that already satisfy most, if not all, of the properties we are looking for in SDS?

I'm keen to avoid reinventing the wheel here.

**Comment by dmitrizagidulin** [comment]
@ianopolous definitely, please do! I think everyone in this group is very keen not to reinvent unnecessarily.

**Comment by bumblefudge** [comment]
I defer to the group on the order of operations, but it might be nice to write a paragraph each about the major prior art options, mentioning specifically *which* of the functional requirements each fails to meet, once that list is mostly finalized. This would be useful to readers of the spec with some, but not all, of the stated functional requirements that prefer older or easier-to-implement systems?

**Comment by ianopolous** [comment]
Okay great. I just wanted to point to a project ([Peergos](https://github.com/peergos/peergos)) that we've been working on for 7 years which has mostly the same requirements as SDS (Actually stronger privacy and security requirements in several cases). It's built on top of ipfs. 

As a TLDR the properties we have include:
* global p2p private filesystem
* strong end to end encryption, and fine grained access control (read only and writable) (capability based, so server's are trustless)
* data model is hash linked data (IPLD) with updates signed by a keypair
* hide metadata from server including file names, mimetypes, file sizes, directory topology, and also who has access to what (the server cannot see who has been granted access to what)
* directories are indistinguishable from small files to the server
* independent of DNS and TLS certificate authorities (though there is a web interface if you trust them)
* handle arbitrarily large files, including streaming, and O(1) seeking
* data can be trivially mirrored which provides live redundancy over the ipfs protocol
* efficent modification of large files
* resistant to quantum computer based attacks - unshared files are already fully post-quantum, shared files currently have a limited time window of vulnerability to a large quantum computer
* access control is done with a version of cryptree, improved to fit in the ipfs data model, which is a stunning data structure (https://github.com/Peergos/Peergos/raw/master/papers/wuala-cryptree.pdf)
* all data is in a merkle-champ (compressed hash-array mapped prefix-trie) which is a great data structure for content addressed mutable data, and plays very well with CRDTs as well. 

You can read more in our [book](https://book.peergos.org)

**Comment by OR13** [comment]
@ianopolous I'd be in favor of a section of Prior art, in the main spec, where we can link to things this. Would you be willing to open a PR?

**Comment by ianopolous** [comment]
Sounds great, I'll do that asap.

**Comment by OR13** [comment]
@nikosft interesting... I'm familar with proxy re-encryption, and the thresholds required... and its always made me nervous ( I don't  trust any system where a threshold of permissioned nodes are required, because NSLs exist, and so do bribes )... but I digress... can you try and ELI5 version of this paper on the issue for others?

**Comment by ianopolous** [comment]
@OR13 Just to clarify, is this the document I should be editing the prior art section into?

https://github.com/Peergos/secure-data-store/blob/master/index.html

**Comment by OR13** [comment]
@ianopolous yes.

**Comment by OR13** [comment]
@ianopolous can you open a PR to add a link, or we should close this issue.

**Comment by ianopolous** [comment]
Yep, sorry. I've been snowed under. I'll try and get to it soon.
