### ISSUE TITLE
Add the term 'Instance' to the terminology section

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/secure-data-store#62]

**Comment by OR13** [comment]
I assume this pretty much entails opening a PR and pasting in something like "instance is a deployment of software meeting the interface requirements for and edv or hub".

**Comment by dmitrizagidulin** [comment]
Implemented by PR #89, recommend we close.

**Comment by dmitrizagidulin** [comment]
Implemented, closing.
